" vimrc for gitbash

set nocompatible

set statusline=%f
set statusline+=%h
set statusline+=%m
set statusline+=%r
set statusline+=\ [%{&ff}]
set statusline+=\ %{exists('g:loaded_fugitive')?FugitiveStatusline():''}
set statusline+=\ (%{strftime(\"%H:%M\ %d/%m/%Y\",getftime(expand(\"%:p\")))})
set statusline+=%=
set statusline+=%l,%c%V
set statusline+=\ %P

set showmatch

set laststatus=2

set novb

set showmode
set showcmd       

set clipboard=unnamed

set wildmenu
set wildmode=list:longest,full

set number
set relativenumber

set hlsearch

set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab autoindent breakindent

set wrap
augroup withoutwrap
    autocmd!
    autocmd FileType qf,fugitiveblame setlocal nowrap
augroup END

set ignorecase
set smartcase

set noautoread

set display=lastline

set nofoldenable
set foldmethod=syntax

set splitbelow splitright

set incsearch

set signcolumn=yes

set colorcolumn=80

filetype plugin indent on

set backspace=indent,eol,start

set noea

set wildignore+=*/.git/**,*/.svn/**,*/.settings/**,*/.metadata/**,*/node_modules/**,*/build/**,*/target/**

set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1

au BufRead,BufNewFile *.liquid setfiletype html
au BufRead,BufNewFile *.njk setfiletype html

set path+=**

" avoid path error when open vim from gitbash launched in vim terminal
if stridx($VIM, '/') == 0
    syntax on
endif

set mouse=a

